### PR TITLE
Various bugfixes + Added a Travis test

### PR DESCRIPTION
**Pull request by muffato**
I have imported all the changes made by @mn1 in his fork as individual commits (authored by @mn1). I also took the liberty of reformatting them and not adding the debug stuff, I hope you don't mind. I've fixed a few more bugs and then managed to integrate this with TravisCI

Summary:
 - Hostnames are not necessarily Container IDs -> Get the Container ID by parsing the active _cgroups_
 - Check that the submission has been successful
 - Fix some stringification issues with large numbers

@mn1 . Would you mind trying this branch out in your tests ? It should work out of the box :crossed_fingers:

### CODE REVIEW

**Comment by mn1** [comment]
Ups, sorry, only saw this now. Will have a look!

**Review by mn1 — APPROVED** [review]
Looks good to me.

**Comment by mn1** [comment]
P.S.: Yes, I'll give this a try next time I run the pipeline!

**Comment by mn1** [comment]
I just did a run of the probemapping pipeline in the embassy cloud with this branch and it worked!

**Comment by muffato** [comment]
Fantastic ! I've merged this PR onto 2.5 and master. Thanks !

**Pull request merged**
